Repository Final-Capstone-Elite-Group/RentUrTechFrontend, pull requests merged in 2022-06, with the labels that each got.

#10 Feature/set up
  .babelrc
  .eslintrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/linters.yml
  .gitignore
  .stylelintrc.json
  MIT.md
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.scss
  src/components/navigation/Navigation.js
  src/components/navigation/navigation.scss
  src/components/protected-route/ProtectedRoute.js
  src/index.js
  src/redux/configure_store.js
  src/redux/equipment/equipment.js
  src/redux/reservation/reservation.js
  src/redux/user/user.js
  src/sass/_index.scss
  src/sass/_variables.scss
  src/sass/global.scss
  src/sass/mixins/_breakpoints.scss
  src/sass/mixins/_placeholder.scss
  src/setupTests.js
Labels: enhancement

#12 Setup Sign-up Component
  package-lock.json
  package.json
  src/App.js
  src/components/navigation/Navigation.js
  src/components/signup/Signup.js
  src/components/signup/signup.module.scss
  src/images/background.jpg
  src/redux/configure_store.js
  src/redux/user/user.js
Labels: enhancement

#13 Login component
  src/App.js
  src/components/login/Login.js
  src/components/signup/Signup.js
  src/redux/configure_store.js
  src/redux/user/user.js
  src/sass/_variables.scss
  src/sass/shared/form.module.scss
Labels: enhancement

#14 Feature/carousel
  package-lock.json
  package.json
  src/App.js
  src/components/button/Button.js
  src/components/button/Button.module.scss
  src/components/button/Button.test.js
  src/components/card/Card.js
  src/components/card/Card.module.scss
  src/components/card/Card.test.js
  src/components/carousel/Carousel.js
  src/components/carousel/Carousel.module.scss
  src/components/carousel/Carousel.test.js
  src/custom-hooks/useWindowDimention.js
  src/redux/configure_store.js
  src/redux/equipment/equipment.js
  src/redux/equipment/equipmentAPI.js
Labels: documentation, enhancement

#15 Reservation Pages
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/components/my-reservations/MyReservations.js
  src/components/my-reservations/my_reservations.module.scss
  src/components/navigation/Navigation.js
  src/components/navigation/navigation.module.scss
  src/components/protected-route/ProtectedRoute.js
  src/components/reserve/Reserve.js
  src/components/reserve/reserve.module.scss
  src/components/signup/Signup.js
  src/index.js
  src/logic/apiClient.js
  src/logic/localStorage.js
  src/logic/toastify.js
  src/redux/configure_store.js
  src/redux/equipment/equipment.js
  src/redux/reservation/reservation.js
  src/redux/user/user.js
  src/sass/_index.scss
  src/sass/_variables.scss
  src/sass/global.scss
  src/sass/mixins/_breakpoints.scss
  src/sass/shared/form.module.scss
Labels: enhancement

#16 Feature/add equipment component
  package-lock.json
  src/App.js
  src/components/equipment/AddEquipment.js
  src/components/login/Login.js
  src/components/signup/Signup.js
  src/redux/equipment/equipmentAPI.js
  src/sass/shared/form.module.scss
Labels: enhancement

#19 Feat/tech
  package-lock.json
  package.json
  src/App.js
  src/__test__/Navigation.test.js
  src/__test__/Reservations.test.js
  src/__test__/__snapshots__/Navigation.test.js.snap
  src/__test__/__snapshots__/Reservations.test.js.snap
  src/__test__/mock/handlers.js
  src/__test__/reservationsReducer.test.js
  src/__test__/test-utils.js
  src/components/button/Button.module.scss
  src/components/card/Card.module.scss
  src/components/carousel/Carousel.js
  src/components/carousel/Carousel.module.scss
  src/components/loading/LoadingCanvas.js
  src/components/loading/loadingCanvas.module.scss
  src/components/login/Login.js
  src/components/my-reservations/MyReservations.js
  src/components/my-reservations/my_reservations.module.scss
  src/components/navigation/Navigation.js
  src/components/reservation/Reservation.js
  src/components/reservation/ReservationParams.js
  src/components/reservation/reservation_components/ReservationBody.js
  src/components/reservation/reservation_components/ReservationForm.js
  src/components/reservation/reservation_components/reservation_form.module.scss
  src/components/reservation/reservation_components/reserve.module.scss
  src/components/reserve/Reserve.js
  src/components/tech/Tech.js
  src/components/tech/tech.module.scss
  src/index.js
  src/logic/apiRequests.js
  src/logic/queries.js
  src/logic/toastify.js
  src/redux/configure_store.js
  src/redux/equipment/equipment.js
  src/redux/menu/menu.js
  src/redux/reservation/reservation.js
  src/sass/_variables.scss
  src/sass/global.scss
  src/sass/mixins/_breakpoints.scss
  src/utils/utils.js
Labels: enhancement

#21 Feature/details component
  package.json
  public/favicon.ico
  src/App.js
  src/components/carousel/Carousel.js
  src/components/color-pallete/ColorPallete.js
  src/components/color-pallete/ColorPallete.test.js
  src/components/details/Details.js
  src/components/details/Details.module.scss
  src/components/details/Details.test.js
  src/redux/configure_store.js
  src/redux/equipment/equipment.js
Labels: enhancement

#26 Feature/modify styles
  src/components/details/Details.js
  src/components/details/Details.module.scss
Labels: enhancement

#27 Feature/details test cases
  package-lock.json
  package.json
  src/__test__/AddEquipment.test.js
  src/__test__/Carousel.test.js
  src/__test__/Reservations.test.js
  src/__test__/__snapshots__/AddEquipment.test.js.snap
  src/__test__/__snapshots__/Reservations.test.js.snap
  src/components/carousel/Carousel.test.js
  src/components/color-pallete/ColorPallete.test.js
  src/components/details/Details.test.js
  src/components/loading/LoadingCanvas.js
Labels: bug

#29 Remove context params
  src/components/loading/LoadingCanvas.js
Labels: bug

#30 Fix not found bug
  src/components/details/Details.js
  src/components/reservation/ReservationParams.js
Labels: bug

#32 Change currency to days
  src/components/details/Details.js
  src/index.js
  src/logic/queries.js
  src/logic/queryClient.js
  src/redux/user/user.js
Labels: bug
